apiVersion: v1
kind: Service
metadata:
  name: qlc
  namespace: qlc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dmx.k8s.ddlia.com
spec:
  selector:
    app: qlc
  type: LoadBalancer
  loadBalancerIP: 10.11.240.254
  ports:
  - name: artnet
    protocol: UDP
    port: 6454
    targetPort: 6454
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9999