apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtmp-ingress
  namespace: live
spec:
  ingressClassName: "cloudflare-tunnel"
  rules:
  - host: k8s.ddlia.com
    http:
      paths:
      - pathType: Prefix
        path: "/live"
        backend:
          service:
            name: rtmp-service
            port:
              number: 80